### ISSUE TITLE
v1.1 Release Checklist

### ISSUE THREAD

**Issue by chris-prener** [shaughnessyar/driftR#23]
To prepare for v1.1 CRAN release:

- [x] all open Issues cleared?

- [x] update logo
- [x] update version number in `DESCRIPTION`
- [x] update version number in `NEWS.md`
- [x] `README` ready to go?

Is the master...

- [x] passing local `R CMD check`?
- [x] passing Appveyor?
- [x] passing Travis CI?
- [x] passing win-builder https://win-builder.r-project.org?

After review complete:

- [x] update `cran-comments.md`
- [x] create new release on GitHub (our GitHub releases don't match our actual release pattern)
- [x] check to make sure Zenodo has picked up new release, and update README if needed

After all check are passed:

- [x] submit for review

**Comment by chris-prener** [comment]
un-checked the version number one - it is still on the dev version number in `NEWS`!

**Comment by chris-prener** [comment]
@shaughnessyar - once the two pull requests are merged - we can create a new release branch and get after this checklist!
